Repository Leeroo-AI/mergoo, pull requests merged in 2024-04, with the labels that each got.

#1 Adding Mixture-of-Adapters features
  .gitignore
  CHANGELOG.md
  examples/compose_lora_bert.py
  examples/compose_lora_mistral.py
  mergoo/compose_experts.py
  mergoo/compose_layers.py
  mergoo/composers/composer_lora_moe.py
  mergoo/composers/composer_moe.py
  notebooks/Mistral_lora_compose_trainer.ipynb
  readme.md
Labels: documentation, enhancement

#3 Update readme.md
  readme.md
Labels: documentation

#5 Llama3 support
  notebooks/integrate_llama3_experts.ipynb
  readme.md
Labels: enhancement

#8 ModuleNotFoundError: No module named 'mergoo.composers'
  mergoo/composers/__init__.py
  mergoo/models/__init__.py
  pyproject.toml
Labels: bug
